version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "daily"
    labels:
      - "npm"
      - "dependencies"

  - package-ecosystem: "composer"
    directory: "/app"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "php"
    allow:
      - dependency-type: "all"