version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "daily"
    labels:
      - "npm"
      - "dependencies"

  - package-ecosystem: "composer"
    directory: "/app"
    registries:
      - spark
    schedule:
      interval: "daily"
    labels:
      - "php"
      - "dependencies"